title: Junfang's Homepage
page-top-title: Junfang Yang
top-section-bg-text: Material and calculational Sciences
home-subtitle: Junfang Yang&ensp;|&ensp;杨俊芳
copyright-text: '&copy; Junfang Yang 2025. All Rights Reserved.'
